### ISSUE TITLE
Stylelint: Allow Sass mixins

### ISSUE THREAD

**Issue by AndrewHaine** [AndrewHaine/silverstripe-webpack-theme#13]
Currently stylelint flags `@include` blocks as an error, adding the following to `.stylelintrc.yml` will whitelist include blocks:

```yaml
at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - 'include'
```
